### ISSUE TITLE
Harvest Jewish Federation of Greater Chattanooga Shofar Newsletters and Chattanooga Gun Violence Activism Oral Histories

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#129]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p16877coll29:Jewish Federation of Greater Chattanooga Shofar Newsletters
* p16877coll30: Chattanooga Gun Violence Activism Oral Histories

We've also updated some existing sets pretty substantially. Is it problematic to re-harvest everything?

**Comment by mlhale7** [comment]
@carolynfrunyon - These two sets have been added. I have created a ticket to re-harvest everything before the next ingest. We need to make a quick update to the XSL transform, so I will wait to do the re-harvest until this work is complete.

**Comment by markpbaggett** [comment]
@mlhale7 a few things:

1. Stytlesheets are applied dynamically.  Therefore, you can harvest / reharvest at any point and any change made to an existing stylesheet will apply without having to do a reharvest.
2. Historically, we haven't always gotten sets added to Repox to DPLA during harvests since that requires a pull request that adds the set to DPLA's ingestion reposiotry.  Because of this, I've been leaving issues open to signify it has something that needs to go into that quarterly pull request and simply adding a comment that explains where things are.  Can we leave this open so we don't forget to add this to the p.r.?
