### ISSUE TITLE
Renaming stylesheets to improve debugging capabilities

### ISSUE THREAD

**Issue by CanOfBees** [DigitalLibraryofTennessee/DLTN_XSLT#13]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform

## Problem with Set or Transform
I'd like to propose renaming the current set of xsl stylesheets to [something like this](https://github.com/CanOfBees/DLTN/tree/bees-the-renaming-ning/XSLT); e.g.
```shell
coreDCtoMODS.xsl --> core-dc-to-mods.xsl
knoxp15136coll1DCtoMODS.xsl --> knox-p15136-coll1-dc-to-mods.xsl 
```
After renaming the files and updating all `xsl:include[@href]` values, we would have a **much** easier time debugging the stylesheets in oXygen. 

*But...* that's a lot of dashes! I'm okay with using `_` (underscores), too, but I'd like to differentiate on *institution*`-`*oai-endpoint*`-`*set*`-`*source-format*`-to-`*output-format*, even though it makes for slightly longer filenames.

**note:** REPOX lowercases the stylesheets internally, so despite the current camelCase filenames in the repository, the applied stylesheets look like `coredctomods.xsl` on the server -- that's why the xsl:include[\@href] values are lowercased.

**Comment by markpbaggett** [comment]
@CanOfBees, I have a few questions:

1. We need to at least acknowledge that we don't have a standardized naming convention for anything--files, sets, etc.  It's all over the place.  I see this tries to bring some order to that, but it's addressing the transform first.  Should we also consider set? If so, we'd likely want to change the file name again to make it adhere to the overall naming schema.
2. Since the repository is leaving our organization and moving to another to encourage participation, we should consider and acknowledge style guide. [This document](http://blog.xml.rocks/xslt-naming-conventions/) acknowledges that the XSLT community is lacking a style guide (although [this guide](https://transpect.github.io/styleguide.html) exists), but I think eventually we'll need to adopt or write some sort of guide as the code opens up.  This isn't so much a question as it is a comment that we should be thinking about this, but if you have any thoughts, please share.
3. This lives in the pull request template, but I'll bring it up here -- can you talk about how this change would affect our current Repox instance? I think there is a relational database that associates sets with transforms.  If I'm thinking about this correctly, this may cause some technical debt in terms of updating the association of each transform to each set.  Can you talk about this? It seems like just changing the case of this wouldn't cause any technical hurdles. What advantages do we get by taking this one step further?

**Comment by CanOfBees** [comment]
@markpbaggett thanks for the feedback, as well as the valuable suggestion from our conversation earlier today. I think I've been too hung up on having semantic names for the stylesheets. Based on the conversation from earlier today, I'm creating a PR that avoids problems with your 1 above. 

As far as your second point: yes, absolutely we need to have something that will let us keep some standards across documents. While oXygen has some built-in functionality for controlling this via the project .xpr, it would be nice to have something that was cross-editor for people who don't have an oxygen license. I'm exploring options.

Re your third point: none of the transforms are cached in the MySQL database, but there still may be some mapping between `utkMODStoMODS.xsl --> utkmodstomods.xsl` that needs to be addressed. There is a public API in REPOX that may give us some control over these theoretical mappings, but it isn't something I've explored sufficiently.

Thanks again for the good questions!

**Comment by CanOfBees** [comment]
[I have a feature branch](https://github.com/CanOfBees/DLTN/tree/bees-the-renaming-ning-II) that is up-to-date/current with the camelCasedStyleSheets in DLTN/master; the new feature branch XSL have lower-cased names, no dashes or other punctuation. If there's any interest in simplifying stylesheet names, this branch may be a good place to restart the conversation.

Based on some recent, non-exhaustive testing, it looks like having a rename `utkMODStoMODS.xsl --> utkmodstomods.xsl` doesn't present any problems for REPOX, so long as tomcat is restarted after the change.

**Comment by markpbaggett** [comment]
@CanOfBees, I'm in favor, and would welcome a pull request.

**Comment by CanOfBees** [comment]
@markpbaggett thanks! I'll work one up today.

**Comment by markpbaggett** [comment]
@CanOfBees do we want to revisit? I know we both thought this was done for some reason.

**Comment by markpbaggett** [comment]
Opened pull request on April 16, 2018.

**Comment by CanOfBees** [comment]
This is long-since discussed, completed, and merged. I'm closing.
