### ISSUE TITLE
One record from UTK CDF has an invalid rights statement

### ISSUE THREAD

**Issue by markpbaggett** [DigitalLibraryofTennessee/DLTN_XSLT#137]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## Problem with Set or Transform

In utk_cdf, there is one record (https://digital.lib.utk.edu/collections/islandora/object/cdf%3A10422/datastream/MODS)  that has an invalid accessCondition.  We either need to make it local, standardize it, or remove the record.

**Comment by mlhale7** [comment]
@markpbaggett - I've went ahead and updated this record so that it matches the statement for the rest of the collection (In Copyright). I've also created [a ticket](https://jirautk.atlassian.net/browse/DPLA-238) to remind us to update repox for this set.

Looking at this collection I noticed that all of our records with a form of "videorecording" aren't showing up in the facets. Do we need to update Solr? Only one shows in the facets, but obviously our ["Other Videos"](https://digital.lib.utk.edu/collections/islandora/search/mods_physicalDescription_form_ms%3A%22video%20recordings%22?type=edismax&cp=collections%3Acdf) link shows we have more.

**Comment by mlhale7** [comment]
This is complete.
