### ISSUE TITLE
Update automated testing for UTK Sets

### ISSUE THREAD

**Issue by CanOfBees** [DigitalLibraryofTennessee/DLTN_XSLT#167]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [x] Discuss Issue or Ask Question
- [ ] Other

## Problem with Set or Transform
This is specific to UTK sets initially.

## Discuss Issue or Ask Question
Per our conversations in PR #166 and Issue #163, it would be a good idea to take a slightly different approach to how we're thinking about testing our XSL transforms. 

*Current* behavior: we run an automated test against an OAI-PMH response; i.e. an XML file (or stream) that includes the full OAI-PMH tree. *However*, REPOX applies our XSL stylesheets against the individual record; e.g. at `record/metadata/*` (as @markpbaggett mentions in #163, this is why the `following::` XPath axis causes problems in the automated testing). 

I'd like to talk about this a bit more: we could either change the identity transform in `utkmodstomods` or, more preferably, we could write a small stylesheet that calls `utkmodstomods` (I'm thinking an include and template match on the specific XPath that we want). But I'm missing something, or not being as thorough. I'd really like to hear thoughts and opinions on this, @markpbaggett and @mlhale7.

Thanks!

**Comment by markpbaggett** [comment]
So, I may have approached this wrong, but I have already rewritten things so that files are split and tested individually.  We got a huge problem now in terms of memory usage and build time.  This test is going to shoot from a couple of minutes to at least 30 the way i have it.

```
#UTK Tests
testValidityOfUTKMODStoMODS() {
    UTK="test_data/utk_mods.txt"
    DATADIR="../working_directory/utk"
    mkdir ${DATADIR}
    cat $UTK | while read line; do
        curl "https://dpla.lib.utk.edu/repox/OAIHandler?verb=ListRecords&metadataPrefix=mods&set=$line" 2>&1 2>/dev/null 1>"$DATADIR/$line.xml"
    done
    mkdir ${DATADIR}/output
    for filename in ${DATADIR}/*.xml; do
        ${SAXON} ${filename} ${STYLESHEETS}/splitmods.xsl 2>&1 2>/dev/null 1>/dev/null
    done
    for filename in ${DATADIR}/output/*.xml; do
        TESTFILE="${filename}.test"
        ${SAXON} ${filename} ${STYLESHEETS}/utkmodstomods.xsl 2>&1 2>/dev/null 1>${TESTFILE}
        RESPONSE=$(xmllint --noout --schema ${DLTNMODS} ${TESTFILE} 2>&1 1>/dev/null | cat)
        assertEquals "${RESPONSE}" "${TESTFILE} validates"
    done
    #rm -rf ${DATADIR}
}

. shunit2
```

and

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.og/2001/XMLSchema"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns="http://www.loc.gov/mods/v3"
                xmlns:oai="http://www.openarchives.org/OAI/2.0/"
                xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-5.xsd"
                exclude-result-prefixes="xs"
                xpath-default-namespace="http://www.loc.gov/mods/v3"
                version="2.0">

    <xsl:output encoding="UTF-8" method="xml" indent="yes"/>
    <xsl:strip-space elements="*"/>

    <!-- match each mods element and write a result document from it -->
    <xsl:template match="oai:metadata">
        <xsl:variable name="file-name" select="preceding-sibling::oai:header/oai:identifier"/>
        <xsl:result-document href="{concat('../working_directory/utk/output/',$file-name,'.xml')}">
            <mods xmlns="http://www.loc.gov/mods/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-5.xsd">
                <xsl:apply-templates select="mods"/>
            </mods>
        </xsl:result-document>
    </xsl:template>

    <!-- identity transform -->
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>

    <xsl:template match="mods">
        <xsl:apply-templates/>
    </xsl:template>

</xsl:stylesheet>
```

Where am I going wrong with thinking here?

**Comment by CanOfBees** [comment]
@markpbaggett I'd need to think about this a little more, but we may not need to do the extra serialization; i.e. my thought (possibly a bad thought) was that we could take the OAI-PMH response, and then apply the XSL stylesheet(s), and then apply `xmllint` to the stdout from that XSL process. 

But let's think about this a little more -- I'll try to get a working example together to point towards.

**Comment by markpbaggett** [comment]
@CanOfBees after doing a little more work and thinking about this, I wonder if this is really worth it.  Here's my line of thinking:

**Why are we doing anything to begin with**:

To have something automated to check for bad data with our incoming data and its associated transform.

**What's the problem right now**:

1. The way we're testing things right now is against a whole OAI response and not individual records which isn't what happens in Repox.
2. If we test the whole response, you have an issue with an existing axes that will need to be changed but in changing won't actually break anything in either place.

**Why not make things exactly like in Repox?**

I can't come up with an *easy* way of testing this. By easy, I mean: not adding a lot of helper things to our existing unit tests or spending a ton of time rethinking everything.

Even if we don't serialze saxon8.7 output to disk, how do we write a transform to easily pass output to xmllint?

**My proposal**:

Since everything is relatively stable now, we alter the transform like in the open pull request and don't make Repox align exactly with our automated tests.  This will save time for the processor and should still be accurate for now.  If in the future, we have a real problem where we have to make them align we can reopen this issue.

Thoughts?

**Comment by CanOfBees** [comment]
@markpbaggett "Sounds good. Thanks for coming."
