### ISSUE TITLE
Reharvest and Add TSLA Sets for September 2019

### ISSUE THREAD

**Issue by jrandlestsla** [DigitalLibraryofTennessee/DLTN_XSLT#192]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [x] Reingest Existing Set

## New Set(s) / Reharvest Existing Set

* p15138coll28
* p15138coll25
* p15138coll27
* p15138coll37
* p15138coll23

## Discuss Issue or Ask Question

* I need to remove a set's records: the alias is conservarts, and it is currently unpublished so the links don't work anymore. This set has been merged into coll28 above. coll28 currently has over 8,000 items and will have over 11,000 by the end of the year, which boosts our item count by a bit!

**Comment by mlhale7** [comment]
@jrandlestsla - apologies for the delay on this. Thanks for getting in this issue way ahead of our September ingest. I have gone ahead and removed conservarts and added coll 28. Collections 25, 27, and 37 have been updated after being checked for the required fields. I'm going to take another look at 23 as it looks like you've used both dc and qdc for this collection (QA analysis attached - [tsla_23.txt](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/files/3477908/tsla_23.txt))

@markpbaggett - would you like to update the IIIF manifests for these? I haven't yet done this, but am happy to if you'd like to take a second to go over things with me.

**Comment by jrandlestsla** [comment]
@mlhale7 no worries on the timing. I updated it when I thought of something to add. 

coll23 has been an issue for us before- it has several thousand metadata-only records. I'm not sure where we left this in previous discussions. The fields are mapped as a lot of our fields are, including some QDC fields. However, I'm not sure why it shows a DC & QDC title/date, as we only have one thing mapped to any Title/Date field. Would it be best to not include those? Will this cause a problem for harvest?

**Comment by markpbaggett** [comment]
@jrandlestsla and @mlhale7,

Some  coll23 advice: I assume this set hasn't been updated since 2015 because it has a lot of "metadata only records."  Sets with metadata only records for us are now "A-OK" to include in DLTN and share with DPLA; we just can't rely on adding them directly via OAI-PMH.  We actually built this for other use cases (Crossroads to Freedom and CMHF), but since I know TSLA has to create metadata only records in some of their collections, I'd encourage us to do the same for these use cases as we do other providers.  It would allow us to increase our numbers and be more flexible.  To include them, we just need to run [dltn_check_and_harvest](https://github.com/DigitalLibraryofTennessee/check_and_harvest) with the "-tu" flag set to "True" and add the harvested files to Repox via file upload.  Checkout the [DLTN technical docs](https://dltn-technical-docs.readthedocs.io/en/latest/) for more details.

@mlhale7 ,

Feel free to take the IIIF work.  You just need to install [the contentdm manifest generator](https://github.com/DigitalLibraryofTennessee/contentdm_catalog_manifest_generator) and run against the set in question.  Then, take the body of the output file and replace [the same section here](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/blob/master/XSLT/catalogs/tsla_catalog.xml).

@mlhale7,

one last thing.  Make sure to add any new sets to [this file](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/blob/master/tests/test_data/tsla_qdc.txt) and open a pull request before adding the set to the [config generator](https://github.com/DigitalLibraryofTennessee/dltn_ingestion3_config_generator).

**Comment by jrandlestsla** [comment]
@markpbaggett Thanks, this is good news. This is the only collection with metadata only records, and we don't have any plans to expand the practice from what I know. But I'll keep this in mind for the future.
