### ISSUE TITLE
Fix mods:location processing in utkMODStoMODS

### ISSUE THREAD

**Issue by CanOfBees** [DigitalLibraryofTennessee/DLTN_XSLT#20]
# Report an Issue

## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [x] Report Problem with an Existing Set or XSL transform

## Problem with Set or Transform
There is some malformed XML in the utkMODStoMODS stylesheet. Ref lines 45-52. We need to analyze and correct the templates here, and ensure that the output is correct for DPLA.

* Please report any information to make finding this issue possible.

**Comment by markpbaggett** [comment]
So, we know what's going on now.  Basically, we have a problem where our MODS input documents have multiple location elements.  There really only needs to be one.  The problem here is that location wants subelements to be sequential: 

```
<xs:sequence>
<xs:element ref="physicalLocation" minOccurs="0" maxOccurs="unbounded"/>
<xs:element ref="shelfLocator" minOccurs="0" maxOccurs="unbounded"/>
<xs:element ref="url" minOccurs="0" maxOccurs="unbounded"/>
<xs:element ref="holdingSimple" minOccurs="0"/><xs:element ref="holdingExternal" minOccurs="0"/></xs:sequence>
```
So, for now, since we need /location/urls, let's just do a copyof for that subelement.  After this, a new ticket to basically get this stuff into one location element in the right order.  Make sense?

**Comment by CanOfBees** [comment]
I have a fix that respects the xs:sequence for the schema, see my PR

**Comment by markpbaggett** [comment]
Fixed.
