### ISSUE TITLE
TSLA March 2020 Ingest

### ISSUE THREAD

**Issue by jrandlestsla** [DigitalLibraryofTennessee/DLTN_XSLT#214]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [x] Reingest Existing Set

## New Set(s) / Reharvest Existing Set

* p15138coll48 (published by Feb 28)
* p15138coll46
* miersphotos
* p15138coll6
* p15138coll27
* p15138coll14
* p15138coll47
* tfd
* p15138coll28
* mckenneyHal

**Comment by mlhale7** [comment]
Hi @jrandlestsla - thanks for sending these ahead of time. I appreciate it! I'm slowly working through checking and adding these sets. I did notice that coll6 has three records that do not have a source value. I've attached a file with the records to this comment. Can you update [these](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/files/4251123/tslacoll6_missingsource.txt) and let me know when I should try out the collection again?

**Comment by jrandlestsla** [comment]
Thanks for catching those. I've updated and reindexed the collection. Let me know if those are still missing source.

**Comment by mlhale7** [comment]
Thanks - coll6 now has source in all of its records.

This doesn't affect ingest for this collection since we seem to be writing in "Tennessee State Library and Archives" for it, but tfd also has
[two records](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/files/4251980/tfd_missingsource.txt) with missing source values.

**Comment by jrandlestsla** [comment]
Thanks, I updated those records.

**Comment by mlhale7** [comment]
All of the collections have been added / updated along with the IIIF manifests.
