### ISSUE TITLE
TSLA- December

### ISSUE THREAD

**Issue by aimeesaunders** [DigitalLibraryofTennessee/DLTN_XSLT#285]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [x ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p15138coll50
* tpc

**Comment by aimeesaunders** [comment]
## New Set(s)

p15138coll50

**Comment by mlhale7** [comment]
@aimeesaunders - thank you for sharing these sets. I've updated and QA'd tpc and it is ready for ingest.

The new set, p15138coll50, currently has 28 records that are missing rights values. I've attached a file identifying those records here 
([missingrights_TSLA50.txt](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/files/10136012/missingrights_TSLA50.txt)). Because rights is a required field, I can't add this set until these records have a rights value added to them. It looks like those that do have rights simply have "Copyright not evaluated", so I think it should be easy to simply add that value to the rest of the items. There definitely are a handful of items that are in the public domain (pre-1900), but refining these statements is not required for DPLA/DLTN. Let me know if you think you can add rights values before Dec. 16th for these records.

**Comment by aimeesaunders** [comment]
We've updated the fields!

**Comment by mlhale7** [comment]
@aimeesaunders - Awesome! Thank you so much. I've updated that set. That brings the total records DLTN is contributing this December to 9719!
