### ISSUE TITLE
IIIF Compliant

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#39]
OCLC has successfully migrated to UTC's CONTENTdm to a new responsive site that is IIIF-compliant. @markpbaggett mentioned that we might need to sign a new agreement with DPLA? Not sure what, if anything, needs to happen, but I wanted to bring it up in case we need to take action. Thanks for looking into this!

**Comment by markpbaggett** [comment]
I think we're supposed to let DPLA know that we have sights who have IIIF image servers and that they want to share things this way. Then, this prompts a new agreement since you're technically no longer sharing just a thumbnail and metadata.  I'll talk to Holly about this and also message Gretchen.

**Comment by markpbaggett** [comment]
@carolynfrunyon I was writing the XSL to add UTC's IIIF manifest to our MODS when I noticed some of these don't have manifests. After writing a script to do some checking on what has a manifest and what does not,  I realized that some (most) objects from UTC don't have a manifest at all.

* [Here is one that has one](https://cdm16877.contentdm.oclc.org/digital/iiif/p16877coll19/7/info.json)
* [Here is one that doesn't have one](https://cdm16877.contentdm.oclc.org/digital/iiif/p16877coll19/202/info.json)

The ContentDM documentation says, "To verify that a CONTENTdm image is supported by the IIIF Image API, a request can be made to return a JSON document providing image information, including width, height, and scaling information."  I want to know when I should expect a IIIF compliant image.  Do you know if this is tied to content model.  

I'm going to run a set by set report to figure out what has a manifest and what does not, but let me know if there is something obvious here that I'm missing. If we can't figure out a way to expect what has a IIIF manifest, we'll probably need to change the way we harvest from you all (add another step to do a manifest check and insert the manifest link prior to it getting to Repox).

**Comment by markpbaggett** [comment]
@carolynfrunyon, a little update.  It looks to me like some of this is due to content model. If ti's a compound object (a book, manuscript, or whatever), there is no manifest for the book itself, but each page has a manifest.  

For example, [this object](https://cdm16877.contentdm.oclc.org/digital/collection/p16877coll1/id/239) should have a manifest [here](https://cdm16877.contentdm.oclc.org/digital/iiif/p16877coll1/239/info.json). While the latter results in a 404, it's pages ([this one for example](https://cdm16877.contentdm.oclc.org/digital/collection/p16877coll1/id/239)) has a [working manifest](https://cdm16877.contentdm.oclc.org/digital/iiif/p16877coll1/235/info.json).

Anyway, let me keep looking at this.  I'll propose something before you all's meeting on Wednesday.

**Comment by markpbaggett** [comment]
Just for the sake of record keeping, of the sets we have currently, here are the objects from UTC with a manifest directly related to the object described in the OAI's descriptive metadata:

1. p16877coll6: 
  * 47 with manifests
  * 29 without
2. p16877coll8
  * 51 with
  * 204 without
3. p16877coll10
  * 90 with
  * 0 without
4. p16877coll11
  * 25 with
  * 24 without
5. p16877coll17
  * 12 with
  * 0 without
6. p16877coll19
  * 14 with
  * 15 without
7. p16877coll23
  * 118 with
  * 191 without

In a separate issue, I'll write a description of what we can do so you all can discuss on Wednesday.
