### ISSUE TITLE
dcterms:bibliographicCitation

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#53]
## Why are You Reporting an Issue

- [ ] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [x] Discuss Issue or Ask Question
- [ ] Other

We are removing dcterms:bibliographicCitation from our standard metadata for CONTENTdm. The field is not automatically updated when we make changes elsewhere, so it's become a bit untenable for us to manage. I'm not sure that we're even sending this to DPLA, but I wanted to make sure to keep you folks in the loop!

https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/blob/master/XSLT/utcqdctomods.xsl

Let me know if I can clarify!
Carolyn

**Comment by markpbaggett** [comment]
@carolynfrunyon, sorry for never getting back about this.  Do you have any examples where this might be present (or might have been present).  I ask because if we pull your old harvests directly from us as qdc, there doesn't look to be a qdc  field
| ------------------------------------------------- | -------------------------- | ----------- | -------------------- |
| _id                                               | ObjectId                   |        3784 | 100.0000000000000000 |
| metadata                                          | Object                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc                      | Object                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.@xmlns:dc            | String                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.@xmlns:dcterms       | String                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.@xmlns:oai_qdc       | String                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.@xmlns:xsi           | String                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.@xsi:schemaLocation  | String                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dc:description       | String (3697),Array (87)   |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dc:format            | String                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dc:identifier        | Array                      |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dc:publisher         | String (986),Array (2798)  |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dc:rights            | String                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dc:source            | Array (1555),String (2229) |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dc:subject           | String (152),Array (3632)  |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dc:title             | String                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dc:type              | Array                      |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dcterms:isPartOf     | String                     |        3784 | 100.0000000000000000 |
| oai_provider                                      | String                     |        3784 | 100.0000000000000000 |
| record_id                                         | String                     |        3784 | 100.0000000000000000 |
| metadata.oai_qdc:qualifieddc.dcterms:created      | Array (71),String (3712)   |        3783 |  99.9735729386892160 |
| metadata.oai_qdc:qualifieddc.dcterms:spatial      | String                     |        3783 |  99.9735729386892160 |
| metadata.oai_qdc:qualifieddc.dc:language          | Array                      |        3780 |  99.8942917547568641 |
| metadata.oai_qdc:qualifieddc.dcterms:extent       | String                     |        3715 |  98.1765327695560188 |
| metadata.oai_qdc:qualifieddc.dc:creator           | String (3571),Array (132)  |        3703 |  97.8594080338266394 |
| metadata.oai_qdc:qualifieddc.dcterms:rightsHolder | String                     |        2903 |  76.7177589852008452 |
| metadata.oai_qdc:qualifieddc.dcterms:license      | String                     |        2761 |  72.9651162790697612 |
| metadata.oai_qdc:qualifieddc.dcterms:alternative  | String                     |        2253 |  59.5401691331923857 |
| metadata.oai_qdc:qualifieddc.dc:contributor       | String                     |         307 |   8.1131078224101483 |
| metadata.oai_qdc:qualifieddc.dcterms:modified     | String                     |          71 |   1.8763213530655392 |

One thought is maybe this was going to dc:description.  Would it be helpful to reharvest everything just in case?

**Comment by carolynfrunyon** [comment]
In that case, maybe this is a non-issue!

**Comment by markpbaggett** [comment]
@carolynfrunyon, maybe, but there is s chance that it could be going to another field.  Do you have any idea of a record that may have had one of these?

**Comment by carolynfrunyon** [comment]
They all had them! But, I'm not 100% sure they ever made it to the OAI feed.

**Comment by markpbaggett** [comment]
eh....nevermind.  i just looked at description, and they aren't there.  i think we're good.
