### ISSUE TITLE
New Sets from UTC

### ISSUE THREAD

**Issue by carolynfrunyon** [DigitalLibraryofTennessee/DLTN_XSLT#66]
## Why are You Reporting an Issue

- [x] Add New Set(s)
- [ ] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [x] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

Only required if you're requesting sets to be added or reharvested.

* p16877coll23
* p16877coll24
* p16877coll25

## Discuss Issue or Ask Question

* I'm in the process of updating our cc licenses. It would be nice to re-harvest all of our sets for the next upload. Nothing in our architecture is changing. We're just giving greater permissions for UTC owned stuff that we want to more openly license.

**Comment by mlhale7** [comment]
Hi @carolynfrunyon - p16877coll23 and p16877coll24 have been QA'd and will be added before the next ingest. Currently p16877coll25 isn't available via your OAI to check it - can you update this? Re-harvesting your sets to reflect more open permissions is fine. Just to confirm, are all of these changes already complete? If so, we can work on getting this done sooner rather than later.

**Comment by carolynfrunyon** [comment]
Hmmm, not sure if CONTENTdm was just taking it's time, but p16877coll25 is available: http://cdm16877.contentdm.oclc.org/oai/oai.php?verb=ListRecords&metadataPrefix=oai_qdc&set=p16877coll25.

**Comment by mlhale7** [comment]
@carolynfrunyon - All of your existing sets have been re-ingested and the new sets listed on this issue have been added.

**Comment by carolynfrunyon** [comment]
Thanks @mlhale7!
