### ISSUE TITLE
TSLA: Ingest new & update existing sets

### ISSUE THREAD

**Issue by jrandlestsla** [DigitalLibraryofTennessee/DLTN_XSLT#74]
## Why are You Reporting an Issue

- [ x] Add New Set(s)
- [ x] Reingest Existing Set
- [ ] Report Problem with an Existing Set or XSL transform
- [ ] Discuss Issue or Ask Question
- [ ] Other

## New Set(s) / Reharvest Existing Set

- p15138coll45
- Fisk
- p15138coll44
- p15138coll31
- p15138coll43
- p15138coll29
- p15138coll39
- p15138coll27
- p15138coll14

**Comment by mlhale7** [comment]
@jrandlestsla - thanks so much for adding these with plenty of time before the ingest.

I have added set 45 (Frank Hodge World War I Papers). I noticed that your medium field seems to have an unnecessary semicolon at the end of the field (value examples: "Documents;", "Military Records;"). It doesn't look like you have multiple values that it's being used to separate. Let me know if you want to clean that out and we can re-ingest this set (though this is not critical).

Currently the other new sets (43 and 44) aren't showing up on your endpoint. Let me know if you can update these so that they appear.

**Comment by jrandlestsla** [comment]
Sure- thanks for the reminder in the meeting invitation. I have fixed the extra semicolons- Project Client does that sometimes when selecting from a controlled vocabulary list. It adds a delimiter to everything when using the list. I have cleaned them up and will index the collection again today.

It's odd that the other sets don't show up- I know there is a recent bug in the OAI-PMH feeds on CONTENTdm sites. I will ask them to make sure those are included and update you when that happens.

**Comment by jrandlestsla** [comment]
43 & 44 sets should be accessible in OAI-PMH now.

**Comment by jrandlestsla** [comment]
Thank you! I checked coll29 and the rights statements there are our standardized statements. Are there particular records that have a different statement? 

Looking at these, all I see are our regular statements. I will work on coll31 and let you know when that is done.

**Comment by jrandlestsla** [comment]
No problem! I am indexing coll31 now so those semicolons should be gone. I also saw something I had to fix in coll29 after your comment- can you please reharvest that? 

Let me know if you see anything else that needs work.

**Comment by mlhale7** [comment]
Thanks Jennifer. I have reharvested both coll29 and coll31. I believe everything in this issue has been addressed so I'm going to close this out.
